version: "3.9"
services:

  postgres:
    image: postgres
    container_name: card-api-pg
    restart: on-failure
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U habrpguser -d habrdb"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  migrate:
    image: liquibase/liquibase
    container_name: card-api-migrate
    restart: "no"
    network_mode: host
    volumes:
      - ./migrate/changelog:/liquibase/changelog/
      - ./migrate/liquibase.local.properties:/liquibase/liquibase.properties
    command: --defaults-file=/liquibase/liquibase.properties --changelog-file=changelog/root.changelog.yml update
    depends_on:
      postgres:
        condition: service_healthy

