# [build]
# rustflags = ["--cfg", "tracing_unstable"]

[env]
RUST_LOG = "adapter=debug,domain=debug,entrypoint=debug"

SYSTEM_SERVER_HOST = "127.0.0.1"
SYSTEM_SERVER_PORT = "8081"

API_SERVER_HOST = "127.0.0.1"
API_SERVER_PORT = "8080"

REPOSITORY_HOST = "127.0.0.1"
REPOSITORY_PORT = "5432"
REPOSITORY_USER = "postgres"
REPOSITORY_PASSWORD = "postgres"
REPOSITORY_DATABASE = "postgres"
REPOSITORY_POOL = "1"

SECRET_PWD_KEY = "ca5418846111e21473d86b42ab51d365d4bae5d6f64de2dd8ba3f58c14b85734"
