[env]
RUST_LOG = "card_api=debug"

SERVER_HOST = "127.0.0.1"
SERVER_PORT = "8080"

REPOSITORY_HOST = "127.0.0.1"
REPOSITORY_PORT = "5432"
REPOSITORY_USER = "postgres"
REPOSITORY_PASSWORD = "postgres"
REPOSITORY_DATABASE = "postgres"
REPOSITORY_POOL = "1"
