@startuml context
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Context.puml

skinparam wrapWidth 300
' skinparam linetype ortho

' LAYOUT_WITH_LEGEND()
' LAYOUT_LANDSCAPE()
LAYOUT_TOP_DOWN()

title Context

Person(client, "Client")
System(api, "CardAPI")
System_Ext(database, "Relational Storage")

Rel_D(client, api, "Uses")
Rel_D(api, database, "Read/Write")

@enduml